<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $data = [
            'Ind. Total',
            'Goals',
            '1st goal',
            'Even/Odd Total',
            'HT-FT',
            'Both teams to score',
            'Half with most goals',
            'Halves result',
            'Penalty',
            'Red card',
            '1st goal',
            '2nd goal',
            'Handicap',
            'Last goal',
            'Time of last goal',
            'Total',
            'Goals in both halves',
            'A sub will score',
            'To win by exactly one goal',
            'Goal in 1st half',
            'Goal in 2nd half"',
            'To score in 1st half',
            'To score in 2nd half',
            'Own goal',
            'Hattrick',
            'Double',
            'Penalty and red card',
            'Both teams to score in 1st half',
            'Both teams to score in 2nd half',
            'Both halves > 1.5 goals',
            'Both halves < 1.5 goals',
            'To win by exactly one goal or a draw',
            'To win to Nil',
            'To win both halves',
            'To win from behind',
            'First goal will be Header',
            'Win 1',
            'Win 2',
            '1st half correct score',
            'First goal in 1st half',
            'First goal in 2nd half',
            'To win either half',
            'Draw in either half',
            'To score its first penalty',
            'To miss its first penalty',
            'Red card',
            'Score draw',
            '1st goal',
            'To score its 1st goal 1',
            'To score its 1st goal 2',
            'Exact number of goals',
            'Total goals in the match',
            'Total goal minutes',
            'Exact number of goals 1',
            'Exact number of goals 2',
            'Goal scored in 1-15 minutes',
            'Goal scored in 16-30 minutes',
            'Goal scored in 31-45 minutes',
            'Goal scored in 46-60 minutes',
            'Goal scored in 61-75 minutes',
            'Goal scored in 76-90 minutes',
            'HT-FT 1-1 and Total Over 2.5',
            'HT-FT 2-2 and Total Over 2.5',
            'First goal scored by',
            'Ind. Total 1st half',
            'Ind. Total 2nd half',
            'Total goals in half',
            'W1 in 1st half or  in the match',
            'W2 in 1st half or in the match',
            'Draw in 1st half or in the match',
            '1st half Total Over (0.5) and 2nd half Тotal Over (1.5)',
            '1st half Total Over (1.5) and 2nd half Total Over (0.5)',
            'W1 and both teams to score',
            'W2 and both teams to score',
            'W1 and 1T Ind. Total Over (1.5)',
            'W2 and 2T Ind. Total Over (1.5)',
            'W1 and 1st half Тotal Over (1.5)',
            'W2 and 1st half Total Over (1.5)',
            'W1 and number of goals: 2-3',
            'W2 and number of goals: 2-3',
            'Goal scored by the kick',
            'Headed goal',
            'Goal in Injury time',
            'Goal will be scored by a direct free kick',
            'Goal during 10 seconds after a corner kick',
            'Throw-in will be before a foul',
            'Yellow card will be before corner',
            'Corner will be before a goal is scored',
            'Wins in 1st half and does not win a match',
            'Both teams to score and Тotal Under',
            'Both teams to score and Тotal Over',
            'To win and Total Under',
            'To win and Total Over',
            'Not to lose and Total Under',
            'Not to lose and Total Over',
            'First to happen',
            'To win from behind',
            'To score from 1 to 10 min',
            'Intervals outcome, min',
            'Penalty in the 1st half',
            'Penalty in the 2nd half',
            'Penalty missed in the match',
            'Penalty scored in the match',
            'First penalty scored by',
            'Red card in the 1st half',
            'Red card in the 2nd half',
            'Each team to win one half',
            'Each team to score under 1.5 goals',
            'Each team to score over 1.5 goals',
            'To lead and not to lose',
            'Goals race',
            'Either team to win difference of 1 goal',
            'Either team to win difference of 2 goals',
            'Either team to win difference of 3 goals',
            'To score 1st goal and fail to win',
            'To score 1st goal and win',
            '2 goals  in a row by one team',
            '3 goals  in a row by one team',
            'To score 2 goals in a row',
            'To score 3 goals in a row',
            'Score draw time is under',
            'Goalkeeper to get red card',
            'Correct score',
            'To score 1st goal and draw',
            'To score 1st goal and to lose',
            'Exact number of goals in 1st half',
            'Short-handed goal',
            'Powerplay goal',
            'Main referee to watch video review of VAR personally',
            'At least one team to score 2 or more goals',
            'At least one team to score 3 or more goals',
            'At least one team to score 4 or more goals',
            'To score 1 or 2 goals',
            'To score 2 or 3 goals',
            'To win 1st half by exactly one goal',
            'Ind. Total of goals',
            'At which half to score more goals',
            '1st half: To win and Тotal Under',
            '1st half: To win and Тotal Over',
            '1st half: Draw and Тotal Over',
            'Asian handicap',
            'Asian total',
            'Asian Ind. Total',
            'Asian handicap 1st half',
            'Asian total 1st half',
            '2nd half correct score',
            '2nd half: To win and Тotal Under',
            '2nd half: To win and Тotal Over',
            '2nd half: Draw and Тotal Over',
            'Both teams to score at least in one half',
            '1st half: Both to score and W1',
            '1st half: Both to score and W2',
            '2nd half: Both to score and W1',
            '2nd half: Both to score and W2',
            'W1 and number of goals: 2-4',
            'W2 and number of goals: 2-4',
            'W1 and number of goals: 3-4',
            'W2 and number of goals: 3-4',
            'W1 and number of goals: 3-5',
            'W2 and number of goals: 3-5',
            'Asian handicap 2nd half',
            'Asian total 2nd half',
            'Handicap 1st half',
            'Handicap 2nd half',
            'Both teams to score in 1st half and at least one not to score in 2nd',
            'At least one team not to score in 1st half and both to score in 2nd',
            'Penalty to be and red card not to be',
            'Penalty not to be and red card to be',
            'Penalty not to be and red card not to be',
            'Penalty or red card',
            'Number of penalties',
            'To score in only one of halves',
            'Win by one or two goals',
            'Win by two or three goals',
            'To score in both halves',
            'Total 1st half',
            'The number in the final score',
        ];

        foreach ($data as $item) {
            \App\Models\BetType::create(
                [
                    'name' => $item
                ]
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        \App\Models\BetType::truncate();
    }
};
